name: Deploy Node.js Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy and Restart Application
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd /var/www/personal_website_official
            git pull
            git fetch --all
            git reset --hard origin/main
            
            # Install dependencies
            npm install
            
            # Build the application
            npm run build
            
            # Delete existing PM2 processes
            pm2 delete personal-website
            
            # Start new PM2 processes
            pm2 start npm --name "personal-website" -i 3 --node-args="--max-old-space-size=2048" -- start
            
            # Save PM2 configuration
            pm2 save
            
            # Reload nginx to ensure it picks up any changes
            sudo systemctl reload nginx
            
            echo "Application updated, rebuilt, and restarted successfully with 3 PM2 instances."
          EOF